/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c8a3c6c7-8f7f-4cb2-8c7b-3f7f4c8b2a1e",
    "aws_cognito_region": "us-east-1", 
    "aws_user_files_s3_bucket": "hotel484f3c92ea9d43a9b243fa720891dbd98be95-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
